### ISSUE TITLE
Browserify + coffeeify 的前端调试方案

### ISSUE THREAD

**Issue by tiye** [coffee-js/languages#55]
#### SPM 更新

开头还是留给 [spm2](http://weibo.com/1748374882/zqaz6pYMG) 发布的广告, 期待能快壮大起来
同时 [CDN](http://cdn.menkr.com/index.html) 也提前放出来, 尽管和 spmjs 源是分开的, 还是觉得挺有意思
我觉得编程就应该更简单, 因此对 CommonJS 语法的喜爱远胜 AMD
SeaJS 的语法不错... 可惜种种原因我个人做玩具首选 Browserify 了
#### Browserify

[Browserify](https://github.com/substack/node-browserify) 看这里, 按描述上它是用 Node 自身的模块机制来加载模块的
模块编译成一个比如 `build.js` 文件, 浏览器这样只要一个 JS 文件较好了
和 Component 项目的不同是这里用的 Node 模块, 而不是另外的办法

使用时要用 `browserify main.js > bundle.js` 这样的命令进行一次编译
在 `main.js` 里 `require` 的其他文件, 会被自动加载过来, 打包到 `bundle.js` 里
`browserify` 命令有更多的参数, 具体就看 README 的说明了
除了 NPM 上安装的模块, 部分 Node 官方模块按文档有浏览器版本直接可用
注意的是 `watch` 命令在[某个版本移除了, 不知什么时候回来](https://github.com/substack/node-browserify/issues/210)

重要的一点是 [SourceMap 支持](https://github.com/substack/node-browserify/issues/259), Component 文档里就没说
Browserify 似乎是一个月前有的 SourceMap 支持, 这以后意义就不同了
加上 `-d` 参数, 生成的 `.js` 脚本就一段 dataURL 形式的 sourceURL 注释
注意开启 Chrome 调试工具的 Enable SourceMap 选项, 然后开始吧
#### coffeeify

Browserify 支持一些[插件](https://github.com/substack/node-browserify#list-of-source-transforms), 可以把其他代码编译到 JS 当中去
对我来说, 主要就是 [coffeeify](https://github.com/substack/coffeeify) 了, 支持 CoffeeScript 的插件
不过现在几个不好, 一个是[模块需要在本地安装才行, 否则会报错]
还有是[需要 `.coffee` 后缀写好, Browerify 才能识别], 而不像 Node 中那样
另外目前[有行号的 bug, 在当前的 coffee `v1.6.2` 版本中会出错](https://github.com/substack/coffeeify/issues/7)
不过按链接说的, 其实 bug 已经修复, 手动才 Github 下载模块替换是可以解决的

这样就能在 Chrome 终端直接看 `.coffee` 代码了, 第一次单步调试 coffee :sparkling_heart: 
不太好的是 @substack [大神本人不写 coffee, README 有提到](https://github.com/substack/coffeeify#maintainers-wanted)
另外写 coffee 的倒是有 [commonjs-everywhere](https://github.com/michaelficarra/commonjs-everywhere) 作者写出来东西
后者, 上次我尝试了没能玩转, 只好往后更新出来的详细文档了, 期待啊
#### 我的尝试

我的 [snowflake](https://github.com/jiyinyiyong/snowflake) 是对此的一个尝试吧, 昨晚调试行号我没调整好的
感觉轻松多... 不过外部模块调用我没尝试, 到时也许有些问题, 再看
另外我的自动编译和浏览器刷新, `browserify` 的 `watch` 参数没好, 绕了点弯子
但以后, 保存代码, 浏览器自动刷新那是必须, 必须把工具做好
#### asm.js

跑题... ASM 的速度好快, JS 编译都常态啊. 各种编译
http://blog.skeeterhouse.com/9032.html
http://kripken.github.com/mloc_emscripten_talk/#/
http://asmjs.org/faq.html

**Comment by tiye** [comment]
近几天看了下 `commonjs-everywhere` 的用法, 觉得可以考虑尝试了
https://github.com/michaelficarra/commonjs-everywhere
相对于 `browserify` 来说的确有一些难得的优点:
- 命令有 `watch` 参数, 关注依赖的内容自动编译, 省了一些麻烦
- 对 CoffeeScript 支持更好, 不需要后缀, 作者本身就是写 coffee 的
- 部分 Browserify 没有自带的 Node 模块在这里是默认的, 方便一些

麻烦当然有还不少:
- `watch` 过程中如果出现错误, 整个程序就会挂掉
- 依赖的是 CoffeeScriptRedux, 文档不多, [`test/`](https://github.com/michaelficarra/CoffeeScriptRedux/tree/master/test) 下的代码看来和 coffee 语法有区别
- [Redux 的函数参数不允许换行, 大概是 Bug](https://github.com/michaelficarra/CoffeeScriptRedux/issues/83), 以后应该会好的
- 我现在的 `index.html build.js` 以及编译命令需要在同一路径, 不清楚具体限制..

相对来说我探索的还太少, `cjsify` 是暴露 AST 的, 信息量更多
话说回来这名字取得, 其实也是 `browserify` 的一个相似方案
很多模块应该也是可一样 `require` 的, 以后再看吧

**Comment by ghost** [comment]
@jiyinyiyong 我觉得你发的这些内容不算语言，和这个论坛的名字偏题了

**Comment by tiye** [comment]
@emerge 还真没注意. 下次可以直接 Close 了, 我把文章转到[博客](http://jiyinyiyong.github.io/blog/posts/130421-browserify-%E5%85%A5%E9%97%A8%E7%AC%94%E8%AE%B0.html)去了

**Comment by island205** [comment]
go ahead Bodule

**Comment by tiye** [comment]
@island205 Bodule 有啥计划? 其实我觉得 `browserify` 的方案已经极致了
对于写 Node, 想要 run JS everywhere 的人, 吸引力和上手程度超高的方案

**Comment by island205** [comment]
@jiyinyiyong 还没什么计划，不过可以作为讨论这些框架的地方。

**Comment by tiye** [comment]
@island205 对啊. 过会我整理一下帖过去.

**Comment by AnnieCyl** [comment]
@jiyinyiyong 
不知道你有没有遇到这个问题：我使用 browserify 的 --debug 生成 sourcemap 来查看源文件，结果发现源文件中的中文都变成乱码了。 
像这样：
![qq20140516162133](https://cloud.githubusercontent.com/assets/2242335/2994808/14f65604-dcd3-11e3-8b9f-3e5d1f694fe6.png)

**Comment by tiye** [comment]
@snowman002000 遇到过, 但很少.. 不知道怎么重现.
应该不是 Browserify 的问题.
一般 *nix 系统里都是 UTF-8 应该不会有问题..
你是在 Windows 下强制编辑器使用 UTF-8 试试?

如果是 Sublime Text 的话, 配置是:

``` js
"default_encoding": "UTF-8",
```

**Comment by AnnieCyl** [comment]
@jiyinyiyong 
我是 win8 64 位系统，使用 webstorm 编辑文件的。但是我的 webstorm 都是设置成 UTF-8 的。
我把我的例子都上传在这个地方：
https://github.com/snowman002000/myrepository
你可以下载试试看会不会出现我说的这个问题。

**Comment by tiye** [comment]
@snowman002000 编码问题我不够熟悉, 不过检测文件信息看你的文件编码是有问题的:

``` js
➤➤ file -I *
README.md:  text/plain; charset=us-ascii
bundle.js:  text/x-c++; charset=utf-8
chinese.js: ERROR: line 22: regexec error 17, (illegal byte sequence); charset=utf-8
index.html: text/html; charset=us-ascii
main.js:    text/x-c++; charset=us-ascii
```
