### ISSUE TITLE
关于“后端只提供数据，前端拼接页面”的话题

### ISSUE THREAD

**Issue by unionx** [coffee-js/languages#61]
这应该是一种比较好的方式。因为如果把拼接页面的工作放到后端的话，就会有很多不方便的地方。也会把View和Control混淆。
现在的问题是，要实现前端拼接页面，一般需要使用哪些工具或者框架？例如Backbone.js和AngularJS？还有其它工具么？

**Comment by undoZen** [comment]
这个问题，在 node.js 出来之后得到了很好的解决。专门有一个前端 UI Server 这种做法，在雪球已经做了近两年。这个 UI Server 就只负责接受请求、渲染页面这种简单的逻辑。因为由前端团队掌控，所以模板复用，以及其他一些性能优化等也好做。

**Comment by ghost** [comment]
完全前端化是正道，做个 json --> dom 的功能，然后 data-json --> ui-json --> dom 即可。回调函数在json中就是Function.toString的字符串，框架规范化一套后即可用。

我也有一点nodejs的后端，逻辑上是代理做前端做不了的事，对高层是透明无缝的，未来浏览器能力增强，完全P2P才是正道。

**Comment by tiye** [comment]
我觉的前端 MVC 基本上是把原先后端的操作整个移到前端, 我接触到的是 Backbone.
单说拼接页面, 我以为你说的模板引擎, 比如 mustache, swig, jucier, ejs..
Backbone 并不限制模板引擎的使用, 虽然默认就有 underscore 的 `template` 可用
AngularJS 听说默认有模板.. 但它是 MVVM 框架而不是 MVC, 还没熟悉

选择一下: http://garann.github.io/template-chooser/

**Comment by unionx** [comment]
我决定先尝试一下AngularJS，看上去似乎可以完成大部分生成页面的功能

**Comment by island205** [comment]
AngularJS能够保证所有的页面都是在前端渲染的
